apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ template "druid.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.router.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "druid.router.fullname" . }}
spec:
  serviceName: {{ template "druid.router.fullname" . }}
  replicas: {{ .Values.router.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "druid.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.router.name }}
  template:
    metadata:
      labels:
        app: {{ template "druid.name" . }}
        component: {{ .Values.router.name }}
        release: {{ .Release.Name }}
        {{- with .Values.router.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
        {{- end }}
    spec:
      {{- if or .Values.router.antiAffinity .Values.router.nodeAffinity }}
      affinity:
      {{- end }}
      {{- if eq .Values.router.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: "{{ template "druid.name" . }}"
                  release: "{{ .Release.Name }}"
                  component: "{{ .Values.router.name }}"
      {{- else if eq .Values.router.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "{{ template "druid.name" . }}"
                  release: "{{ .Release.Name }}"
                  component: "{{ .Values.router.name }}"
      {{- end }}
      {{- with .Values.router.nodeAffinity }}
        nodeAffinity:
{{ toYaml . | indent 10 }}
      {{- end }}
{{- if .Values.router.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.router.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.router.tolerations }}
      tolerations:
{{ toYaml .Values.router.tolerations | indent 8 }}
{{- end }}
      containers:
      - name: druid
        args: [ "router" ]
        env:
        {{- if .Values.zookeeper.enabled }}
        - name: ZOOKEEPER_HOST
          value: {{ .Release.Name }}-cp-zookeeper-headless:2181
        {{- else }}
        - name: ZOOKEEPER_HOST
          value: {{ .Release.Name }}-cp-zookeeper-headless:2181
        {{- end }}
        - name: JAVA_OPTS
          value: {{ .Values.router.javaOpts }}
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: druid_extensions_loadList
          value: '["postgresql-metadata-storage", "druid-kafka-indexing-service", "druid-avro-extensions"]'

        - name: druid_indexer_runner_javaOptsArray
          value: '["-server", "-Xmx1g", "-Xms1g", "-XX:MaxDirectMemorySize=3g", "-Duser.timezone=UTC", "-Dfile.encoding=UTF-8", "-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"]'

        - name: DRUID_LOG4J
          value: '<?xml version="1.0" encoding="UTF-8" ?><Configuration status="WARN"><Appenders><Console name="Console" target="SYSTEM_OUT"><PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/></Console></Appenders><Loggers><Root level="info"><AppenderRef ref="Console"/></Root><Logger name="org.apache.druid.jetty.RequestLog" additivity="false" level="DEBUG"><AppenderRef ref="Console"/></Logger></Loggers></Configuration>'
        resources:
{{ toYaml .Values.router.resources | indent 12 }}
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: {{ .Values.router.port }}
        readinessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: {{ .Values.router.port }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.router.port }}
          name: http
        volumeMounts:
        - mountPath: /opt/druid/var
          name: data
        securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
  {{- if not .Values.router.persistence.enabled }}
      volumes:
      - name: data
        emptyDir: {}
  {{- end }}
  updateStrategy:
    type: {{ .Values.router.updateStrategy.type }}
  {{- if .Values.router.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - {{ .Values.router.persistence.accessMode | quote }}
    {{- if .Values.router.persistence.storageClass }}
    {{- if (eq "-" .Values.router.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.router.persistence.storageClass }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: "{{ .Values.router.persistence.size }}"
  {{ end }}
